import unittest
from meu_grafo_lista_adj import *
from bibgrafo.grafo_errors import *
from bibgrafo.aresta import Aresta


class TestGrafo(unittest.TestCase):

    def setUp(self):
        # Ciclo
        self.c1 = MeuGrafo()
        self.c1.adiciona_vertice('A')
        self.c1.adiciona_vertice('B')
        self.c1.adiciona_vertice('C')
        self.c1.adiciona_vertice('D')
        self.c1.adiciona_vertice('E')
        self.c1.adiciona_aresta('a1', 'B', 'B')
        self.c1.adiciona_aresta('a2', 'A', 'E')
        self.c1.adiciona_aresta('a3', 'E', 'B')
        self.c1.adiciona_aresta('a4', 'B', 'A')
        
        self.c2 = MeuGrafo()
        self.c2.adiciona_vertice('A')
        self.c2.adiciona_vertice('B')
        self.c2.adiciona_vertice('C')
        self.c2.adiciona_vertice('D')
        self.c2.adiciona_aresta('a1', 'A', 'B')
        self.c2.adiciona_aresta('a2', 'B', 'C')
        self.c2.adiciona_aresta('a3', 'C', 'D')
        self.c2.adiciona_aresta('a4', 'D', 'B')
        
        # Grafo do Roteiro 2
        self.g_t1 = MeuGrafo()
        self.g_t1.adiciona_vertice("A")
        self.g_t1.adiciona_vertice("B")
        self.g_t1.adiciona_vertice("C")
        self.g_t1.adiciona_vertice("D")
        self.g_t1.adiciona_vertice("E")
        self.g_t1.adiciona_vertice("F")
        self.g_t1.adiciona_vertice("G")
        self.g_t1.adiciona_vertice("H")
        self.g_t1.adiciona_vertice("I")
        self.g_t1.adiciona_vertice("J")
        self.g_t1.adiciona_vertice("K")
        self.g_t1.adiciona_aresta('1', 'A', 'B')
        self.g_t1.adiciona_aresta('2', 'A', 'G')
        self.g_t1.adiciona_aresta('3', 'A', 'J')
        self.g_t1.adiciona_aresta('4', 'K', 'G')
        self.g_t1.adiciona_aresta('5', 'K', 'J')
        self.g_t1.adiciona_aresta('6', 'J', 'G')
        self.g_t1.adiciona_aresta('7', 'J', 'I')
        self.g_t1.adiciona_aresta('8', 'I', 'G')
        self.g_t1.adiciona_aresta('9', 'G', 'H')
        self.g_t1.adiciona_aresta('10', 'H', 'F')
        self.g_t1.adiciona_aresta('11', 'F', 'B')
        self.g_t1.adiciona_aresta('12', 'B', 'G')
        self.g_t1.adiciona_aresta('13', 'B', 'C')
        self.g_t1.adiciona_aresta('14', 'C', 'D')
        self.g_t1.adiciona_aresta('15', 'D', 'E')
        self.g_t1.adiciona_aresta('16', 'D', 'B')
        self.g_t1.adiciona_aresta('17', 'E', 'B')
        
        self.g_t2 = MeuGrafo()
        self.g_t2.adiciona_vertice("A")
        self.g_t2.adiciona_aresta('1', 'A', 'A')
        
        self.g_t3 = MeuGrafo()
        self.g_t3.adiciona_vertice("A")
        self.g_t3.adiciona_vertice("B")
        self.g_t3.adiciona_aresta('1', 'A', 'B')
        
        self.g_t4 = MeuGrafo()
        self.g_t4.adiciona_vertice("A")
        self.g_t4.adiciona_vertice("B")
        self.g_t4.adiciona_vertice("C")
        self.g_t4.adiciona_aresta('1', 'A', 'B')
        self.g_t4.adiciona_aresta('2', 'A', 'C')
        self.g_t4.adiciona_aresta('3', 'B', 'C')
        
        # Cíclico
        self.g_t5 = MeuGrafo()
        self.g_t5.adiciona_vertice("A")
        self.g_t5.adiciona_vertice("B")
        self.g_t5.adiciona_vertice("C")
        self.g_t5.adiciona_aresta('1', 'A', 'B')
        self.g_t5.adiciona_aresta('2', 'B', 'C')
        self.g_t5.adiciona_aresta('3', 'C', 'A')
        
        # Acíclico
        self.g_t6 = MeuGrafo()
        self.g_t6.adiciona_vertice("A")
        self.g_t6.adiciona_vertice("B")
        self.g_t6.adiciona_vertice("C")
        self.g_t6.adiciona_aresta('1', 'A', 'B')
        self.g_t6.adiciona_aresta('2', 'B', 'C')
        
        # Sem arestas
        self.g_t7 = MeuGrafo()
        self.g_t7.adiciona_vertice("A")
        self.g_t7.adiciona_vertice("B")
        self.g_t7.adiciona_vertice("C")
        
        # Grafo da Paraíba
        self.g_p = MeuGrafo()
        self.g_p.adiciona_vertice("J")
        self.g_p.adiciona_vertice("C")
        self.g_p.adiciona_vertice("E")
        self.g_p.adiciona_vertice("P")
        self.g_p.adiciona_vertice("M")
        self.g_p.adiciona_vertice("T")
        self.g_p.adiciona_vertice("Z")
        self.g_p.adiciona_aresta('a1', 'J', 'C')
        self.g_p.adiciona_aresta('a2', 'C', 'E')
        self.g_p.adiciona_aresta('a3', 'C', 'E')
        self.g_p.adiciona_aresta('a4', 'P', 'C')
        self.g_p.adiciona_aresta('a5', 'P', 'C')
        self.g_p.adiciona_aresta('a6', 'T', 'C')
        self.g_p.adiciona_aresta('a7', 'M', 'C')
        self.g_p.adiciona_aresta('a8', 'M', 'T')
        self.g_p.adiciona_aresta('a9', 'T', 'Z')

        # Clone do Grafo da Paraíba para ver se o método equals está funcionando
        self.g_p2 = MeuGrafo()
        self.g_p2.adiciona_vertice("J")
        self.g_p2.adiciona_vertice("C")
        self.g_p2.adiciona_vertice("E")
        self.g_p2.adiciona_vertice("P")
        self.g_p2.adiciona_vertice("M")
        self.g_p2.adiciona_vertice("T")
        self.g_p2.adiciona_vertice("Z")
        self.g_p2.adiciona_aresta('a1', 'J', 'C')
        self.g_p2.adiciona_aresta('a2', 'C', 'E')
        self.g_p2.adiciona_aresta('a3', 'C', 'E')
        self.g_p2.adiciona_aresta('a4', 'P', 'C')
        self.g_p2.adiciona_aresta('a5', 'P', 'C')
        self.g_p2.adiciona_aresta('a6', 'T', 'C')
        self.g_p2.adiciona_aresta('a7', 'M', 'C')
        self.g_p2.adiciona_aresta('a8', 'M', 'T')
        self.g_p2.adiciona_aresta('a9', 'T', 'Z')

        # Outro clone do Grafo da Paraíba para ver se o método equals está funcionando
        # Esse tem um pequena diferença na primeira aresta
        self.g_p3 = MeuGrafo()
        self.g_p3.adiciona_vertice("J")
        self.g_p3.adiciona_vertice("C")
        self.g_p3.adiciona_vertice("E")
        self.g_p3.adiciona_vertice("P")
        self.g_p3.adiciona_vertice("M")
        self.g_p3.adiciona_vertice("T")
        self.g_p3.adiciona_vertice("Z")
        self.g_p3.adiciona_aresta('a', 'J', 'C')
        self.g_p3.adiciona_aresta('a2', 'C', 'E')
        self.g_p3.adiciona_aresta('a3', 'C', 'E')
        self.g_p3.adiciona_aresta('a4', 'P', 'C')
        self.g_p3.adiciona_aresta('a5', 'P', 'C')
        self.g_p3.adiciona_aresta('a6', 'T', 'C')
        self.g_p3.adiciona_aresta('a7', 'M', 'C')
        self.g_p3.adiciona_aresta('a8', 'M', 'T')
        self.g_p3.adiciona_aresta('a9', 'T', 'Z')

        # Outro clone do Grafo da Paraíba para ver se o método equals está funcionando
        # Esse tem um pequena diferença na segunda aresta
        self.g_p4 = MeuGrafo()
        self.g_p4.adiciona_vertice("J")
        self.g_p4.adiciona_vertice("C")
        self.g_p4.adiciona_vertice("E")
        self.g_p4.adiciona_vertice("P")
        self.g_p4.adiciona_vertice("M")
        self.g_p4.adiciona_vertice("T")
        self.g_p4.adiciona_vertice("Z")
        self.g_p4.adiciona_aresta('a1', 'J', 'C')
        self.g_p4.adiciona_aresta('a2', 'J', 'E')
        self.g_p4.adiciona_aresta('a3', 'C', 'E')
        self.g_p4.adiciona_aresta('a4', 'P', 'C')
        self.g_p4.adiciona_aresta('a5', 'P', 'C')
        self.g_p4.adiciona_aresta('a6', 'T', 'C')
        self.g_p4.adiciona_aresta('a7', 'M', 'C')
        self.g_p4.adiciona_aresta('a8', 'M', 'T')
        self.g_p4.adiciona_aresta('a9', 'T', 'Z')

        # Grafo da Paraíba sem arestas paralelas
        self.g_p_sem_paralelas = MeuGrafo()
        self.g_p_sem_paralelas.adiciona_vertice("J")
        self.g_p_sem_paralelas.adiciona_vertice("C")
        self.g_p_sem_paralelas.adiciona_vertice("E")
        self.g_p_sem_paralelas.adiciona_vertice("P")
        self.g_p_sem_paralelas.adiciona_vertice("M")
        self.g_p_sem_paralelas.adiciona_vertice("T")
        self.g_p_sem_paralelas.adiciona_vertice("Z")
        self.g_p_sem_paralelas.adiciona_aresta('a1', 'J', 'C')
        self.g_p_sem_paralelas.adiciona_aresta('a2', 'C', 'E')
        self.g_p_sem_paralelas.adiciona_aresta('a3', 'P', 'C')
        self.g_p_sem_paralelas.adiciona_aresta('a4', 'T', 'C')
        self.g_p_sem_paralelas.adiciona_aresta('a5', 'M', 'C')
        self.g_p_sem_paralelas.adiciona_aresta('a6', 'M', 'T')
        self.g_p_sem_paralelas.adiciona_aresta('a7', 'T', 'Z')

        # Grafos completos

        self.g_c2 = MeuGrafo()
        self.g_c2.adiciona_vertice("Nina")
        self.g_c2.adiciona_vertice("Maria")
        self.g_c2.adiciona_aresta('amiga', 'Nina', 'Maria')

        self.g_c3 = MeuGrafo()
        self.g_c3.adiciona_vertice("Único")
        
        # Grafos com laco
        self.g_l1 = MeuGrafo()
        self.g_l1.adiciona_vertice("A")
        self.g_l1.adiciona_vertice("B")
        self.g_l1.adiciona_vertice("C")
        self.g_l1.adiciona_vertice("D")
        self.g_l1.adiciona_aresta('a1', 'A', 'A')
        self.g_l1.adiciona_aresta('a2', 'A', 'B')
        self.g_l1.adiciona_aresta('a3', 'A', 'A')

        self.g_l2 = MeuGrafo()
        self.g_l2.adiciona_vertice("A")
        self.g_l2.adiciona_vertice("B")
        self.g_l2.adiciona_vertice("C")
        self.g_l2.adiciona_vertice("D")
        self.g_l2.adiciona_aresta('a1', 'A', 'B')
        self.g_l2.adiciona_aresta('a2', 'B', 'B')
        self.g_l2.adiciona_aresta('a3', 'B', 'A')

        self.g_l3 = MeuGrafo()
        self.g_l3.adiciona_vertice("A")
        self.g_l3.adiciona_vertice("B")
        self.g_l3.adiciona_vertice("C")
        self.g_l3.adiciona_vertice("D")
        self.g_l3.adiciona_aresta('a1', 'C', 'A')
        self.g_l3.adiciona_aresta('a2', 'C', 'C')
        self.g_l3.adiciona_aresta('a3', 'D', 'D')
        self.g_l3.adiciona_aresta('a4', 'D', 'D')

        self.g_l4 = MeuGrafo()
        self.g_l4.adiciona_vertice("D")
        self.g_l4.adiciona_aresta('a1', 'D', 'D')

        self.g_l5 = MeuGrafo()
        self.g_l5.adiciona_vertice("C")
        self.g_l5.adiciona_vertice("D")
        self.g_l5.adiciona_aresta('a1', 'D', 'C')
        self.g_l5.adiciona_aresta('a2', 'C', 'C')

        # Grafos desconexos
        self.g_d = MeuGrafo()
        self.g_d.adiciona_vertice("A")
        self.g_d.adiciona_vertice("B")
        self.g_d.adiciona_vertice("C")
        self.g_d.adiciona_vertice("D")
        self.g_d.adiciona_aresta('asd', 'A', 'B')

        self.g_d2 = MeuGrafo()
        self.g_d2.adiciona_vertice("A")
        self.g_d2.adiciona_vertice("B")
        self.g_d2.adiciona_vertice("C")
        self.g_d2.adiciona_vertice("D")
        
        # Resultados para DFS
        
        self.g_t1_dfs = MeuGrafo()
        self.g_t1_dfs.adiciona_vertice("A")
        self.g_t1_dfs.adiciona_vertice("B")
        self.g_t1_dfs.adiciona_vertice("C")
        self.g_t1_dfs.adiciona_vertice("D")
        self.g_t1_dfs.adiciona_vertice("E")
        self.g_t1_dfs.adiciona_vertice("F")
        self.g_t1_dfs.adiciona_vertice("G")
        self.g_t1_dfs.adiciona_vertice("H")
        self.g_t1_dfs.adiciona_vertice("I")
        self.g_t1_dfs.adiciona_vertice("J")
        self.g_t1_dfs.adiciona_vertice("K")
        self.g_t1_dfs.adiciona_aresta('4', 'K', 'G')
        self.g_t1_dfs.adiciona_aresta('2', 'G', 'A')
        self.g_t1_dfs.adiciona_aresta('1', 'A', 'B')
        self.g_t1_dfs.adiciona_aresta('11', 'B', 'F')
        self.g_t1_dfs.adiciona_aresta('10', 'F', 'H')
        self.g_t1_dfs.adiciona_aresta('13', 'B', 'C')
        self.g_t1_dfs.adiciona_aresta('14', 'C', 'D')
        self.g_t1_dfs.adiciona_aresta('15', 'D', 'E')
        self.g_t1_dfs.adiciona_aresta('3', 'A', 'J')
        self.g_t1_dfs.adiciona_aresta('7', 'J', 'I')
        
        self.g_t2_dfs = MeuGrafo()
        self.g_t2_dfs.adiciona_vertice("A")
        
        self.g_t3_dfs = MeuGrafo()
        self.g_t3_dfs.adiciona_vertice("A")
        self.g_t3_dfs.adiciona_vertice("B")
        self.g_t3_dfs.adiciona_aresta('1', 'B', 'A')
        
        self.g_t4_dfs = MeuGrafo()
        self.g_t4_dfs.adiciona_vertice("A")
        self.g_t4_dfs.adiciona_vertice("B")
        self.g_t4_dfs.adiciona_vertice("C")
        self.g_t4_dfs.adiciona_aresta('1', 'B', 'A')
        self.g_t4_dfs.adiciona_aresta('2', 'A', 'C')
        
        self.g_t5_dfs = MeuGrafo()
        self.g_t5_dfs.adiciona_vertice("A")
        self.g_t5_dfs.adiciona_vertice("B")
        self.g_t5_dfs.adiciona_vertice("C")
        self.g_t5_dfs.adiciona_aresta('1', 'A', 'B')
        self.g_t5_dfs.adiciona_aresta('2', 'B', 'C')
        
        self.g_t6_dfs = MeuGrafo()
        self.g_t6_dfs.adiciona_vertice("A")
        self.g_t6_dfs.adiciona_vertice("B")
        self.g_t6_dfs.adiciona_vertice("C")
        self.g_t6_dfs.adiciona_aresta('2', 'C', 'B')
        self.g_t6_dfs.adiciona_aresta('1', 'B', 'A')
        
        self.g_t7_dfs = MeuGrafo()
        self.g_t7_dfs.adiciona_vertice("A")
        self.g_t7_dfs.adiciona_vertice("B")
        self.g_t7_dfs.adiciona_vertice("C")
        
        self.g_p_dfs = MeuGrafo()
        self.g_p_dfs.adiciona_vertice("J")
        self.g_p_dfs.adiciona_vertice("C")
        self.g_p_dfs.adiciona_vertice("E")
        self.g_p_dfs.adiciona_vertice("P")
        self.g_p_dfs.adiciona_vertice("M")
        self.g_p_dfs.adiciona_vertice("T")
        self.g_p_dfs.adiciona_vertice("Z")
        self.g_p_dfs.adiciona_aresta('a1', 'J', 'C')
        self.g_p_dfs.adiciona_aresta('a2', 'C', 'E')
        self.g_p_dfs.adiciona_aresta('a4', 'P', 'C')
        self.g_p_dfs.adiciona_aresta('a6', 'T', 'C')
        self.g_p_dfs.adiciona_aresta('a7', 'M', 'C')
        self.g_p_dfs.adiciona_aresta('a9', 'T', 'Z')
        
        self.g_p4_dfs = MeuGrafo()
        self.g_p4_dfs.adiciona_vertice("J")
        self.g_p4_dfs.adiciona_vertice("C")
        self.g_p4_dfs.adiciona_vertice("E")
        self.g_p4_dfs.adiciona_vertice("P")
        self.g_p4_dfs.adiciona_vertice("M")
        self.g_p4_dfs.adiciona_vertice("T")
        self.g_p4_dfs.adiciona_vertice("Z")
        self.g_p4_dfs.adiciona_aresta('a1', 'J', 'C')
        self.g_p4_dfs.adiciona_aresta('a2', 'E', 'J')
        self.g_p4_dfs.adiciona_aresta('a4', 'C', 'P')
        self.g_p4_dfs.adiciona_aresta('a6', 'C', 'T')
        self.g_p4_dfs.adiciona_aresta('a8', 'T', 'M')
        self.g_p4_dfs.adiciona_aresta('a9', 'T', 'Z')
        
        self.g_p_sem_paralelas_dfs = MeuGrafo()
        self.g_p_sem_paralelas_dfs.adiciona_vertice("J")
        self.g_p_sem_paralelas_dfs.adiciona_vertice("C")
        self.g_p_sem_paralelas_dfs.adiciona_vertice("E")
        self.g_p_sem_paralelas_dfs.adiciona_vertice("P")
        self.g_p_sem_paralelas_dfs.adiciona_vertice("M")
        self.g_p_sem_paralelas_dfs.adiciona_vertice("T")
        self.g_p_sem_paralelas_dfs.adiciona_vertice("Z")
        self.g_p_sem_paralelas_dfs.adiciona_aresta('a1', 'C', 'J')
        self.g_p_sem_paralelas_dfs.adiciona_aresta('a2', 'C', 'E')
        self.g_p_sem_paralelas_dfs.adiciona_aresta('a3', 'C', 'P')
        self.g_p_sem_paralelas_dfs.adiciona_aresta('a4', 'T', 'C')
        self.g_p_sem_paralelas_dfs.adiciona_aresta('a5', 'C', 'M')
        self.g_p_sem_paralelas_dfs.adiciona_aresta('a7', 'Z', 'T')
        
        self.g_c_dfs = MeuGrafo()
        self.g_c_dfs.adiciona_vertice("J")
        self.g_c_dfs.adiciona_vertice("C")
        self.g_c_dfs.adiciona_vertice("E")
        self.g_c_dfs.adiciona_vertice("P")
        self.g_c_dfs.adiciona_aresta('a1', 'J', 'C')
        self.g_c_dfs.adiciona_aresta('a4', 'C', 'E')
        self.g_c_dfs.adiciona_aresta('a6', 'E', 'P')
        
        self.g_l3_dfs = MeuGrafo()
        self.g_l3_dfs.adiciona_vertice("A")
        self.g_l3_dfs.adiciona_vertice("C")
        self.g_l3_dfs.adiciona_aresta('a1', 'C', 'A')
        
        self.g_d2_dfs = MeuGrafo()
        self.g_d2_dfs.adiciona_vertice("A")
        self.g_d2_dfs.adiciona_vertice("B")
        self.g_d2_dfs.adiciona_vertice("C")
        self.g_d2_dfs.adiciona_vertice("D")
        
        self.g_c = MeuGrafo()
        self.g_c.adiciona_vertice("J")
        self.g_c.adiciona_vertice("C")
        self.g_c.adiciona_vertice("E")
        self.g_c.adiciona_vertice("P")
        self.g_c.adiciona_aresta('a1', 'J', 'C')
        self.g_c.adiciona_aresta('a2', 'J', 'E')
        self.g_c.adiciona_aresta('a3', 'J', 'P')
        self.g_c.adiciona_aresta('a4', 'E', 'C')
        self.g_c.adiciona_aresta('a5', 'P', 'C')
        self.g_c.adiciona_aresta('a6', 'P', 'E')
        
        # Resultados possíveis para o método BFS
        self.g_t1_bfs = MeuGrafo()
        self.g_t1_bfs.adiciona_vertice("A")
        self.g_t1_bfs.adiciona_vertice("B")
        self.g_t1_bfs.adiciona_vertice("C")
        self.g_t1_bfs.adiciona_vertice("D")
        self.g_t1_bfs.adiciona_vertice("E")
        self.g_t1_bfs.adiciona_vertice("F")
        self.g_t1_bfs.adiciona_vertice("G")
        self.g_t1_bfs.adiciona_vertice("H")
        self.g_t1_bfs.adiciona_vertice("I")
        self.g_t1_bfs.adiciona_vertice("J")
        self.g_t1_bfs.adiciona_vertice("K")
        self.g_t1_bfs.adiciona_aresta('4', 'K', 'G')
        self.g_t1_bfs.adiciona_aresta('5', 'K', 'J')
        self.g_t1_bfs.adiciona_aresta('2', 'G', 'A')
        self.g_t1_bfs.adiciona_aresta('8', 'G', 'I')
        self.g_t1_bfs.adiciona_aresta('9', 'G', 'H')
        self.g_t1_bfs.adiciona_aresta('12', 'G', 'B')
        self.g_t1_bfs.adiciona_aresta('10', 'H', 'F')
        self.g_t1_bfs.adiciona_aresta('13', 'B', 'C') 
        self.g_t1_bfs.adiciona_aresta('16', 'B', 'D')
        self.g_t1_bfs.adiciona_aresta('17', 'B', 'E')
        
        self.g_p_bfs = MeuGrafo()
        self.g_p_bfs.adiciona_vertice("J")
        self.g_p_bfs.adiciona_vertice("C")
        self.g_p_bfs.adiciona_vertice("E")
        self.g_p_bfs.adiciona_vertice("P")
        self.g_p_bfs.adiciona_vertice("T")
        self.g_p_bfs.adiciona_vertice("M")
        self.g_p_bfs.adiciona_vertice("Z")
        self.g_p_bfs.adiciona_aresta('a6', 'T', 'C')
        self.g_p_bfs.adiciona_aresta('a8', 'T', 'M')
        self.g_p_bfs.adiciona_aresta('a9', 'T', 'Z')
        self.g_p_bfs.adiciona_aresta('a1', 'C', 'J')
        self.g_p_bfs.adiciona_aresta('a2', 'C', 'E')
        self.g_p_bfs.adiciona_aresta('a4', 'C', 'P')

        self.g_d2_bfs = MeuGrafo()
        self.g_d2_bfs.adiciona_vertice("A")
        self.g_d2_bfs.adiciona_vertice("B")
        self.g_d2_bfs.adiciona_vertice("C")
        self.g_d2_bfs.adiciona_vertice("D")

        self.g_l3_bfs = MeuGrafo()
        self.g_l3_bfs.adiciona_vertice("A")
        self.g_l3_bfs.adiciona_vertice("C")
        self.g_l3_bfs.adiciona_aresta('a1', 'A', 'C')

        self.g_c_bfs = MeuGrafo()
        self.g_c_bfs.adiciona_vertice("J")
        self.g_c_bfs.adiciona_vertice("C")
        self.g_c_bfs.adiciona_vertice("E")
        self.g_c_bfs.adiciona_vertice("P")
        self.g_c_bfs.adiciona_aresta('a1', 'J', 'C')
        self.g_c_bfs.adiciona_aresta('a2', 'J', 'E')
        self.g_c_bfs.adiciona_aresta('a3', 'J', 'P')
        
        self.g_t2_bfs = MeuGrafo()
        self.g_t2_bfs.adiciona_vertice("A")
        
        self.g_t3_bfs = MeuGrafo()
        self.g_t3_bfs.adiciona_vertice("A")
        self.g_t3_bfs.adiciona_vertice("B")
        self.g_t3_bfs.adiciona_aresta('1', 'B', 'A')
        
        self.g_t4_bfs = MeuGrafo()
        self.g_t4_bfs.adiciona_vertice("A")
        self.g_t4_bfs.adiciona_vertice("B")
        self.g_t4_bfs.adiciona_vertice("C")
        self.g_t4_bfs.adiciona_aresta('1', 'B', 'A')
        self.g_t4_bfs.adiciona_aresta('3', 'B', 'C')
        
        self.g_t5_bfs = MeuGrafo()
        self.g_t5_bfs.adiciona_vertice("A")
        self.g_t5_bfs.adiciona_vertice("B")
        self.g_t5_bfs.adiciona_vertice("C")
        self.g_t5_bfs.adiciona_aresta('1', 'A', 'B')
        self.g_t5_bfs.adiciona_aresta('3', 'A', 'C')
        
        self.g_t6_bfs = MeuGrafo()
        self.g_t6_bfs.adiciona_vertice("A")
        self.g_t6_bfs.adiciona_vertice("B")
        self.g_t6_bfs.adiciona_vertice("C")
        self.g_t6_bfs.adiciona_aresta('2', 'C', 'B')
        self.g_t6_bfs.adiciona_aresta('1', 'B', 'A')
        
        self.g_t7_bfs = MeuGrafo()
        self.g_t7_bfs.adiciona_vertice("A")
        self.g_t7_bfs.adiciona_vertice("B")
        self.g_t7_bfs.adiciona_vertice("C")

    def test_adiciona_aresta(self):
        self.assertTrue(self.g_p.adiciona_aresta('a10', 'J', 'C'))
        a = Aresta("zxc", self.g_p.get_vertice("C"), self.g_p.get_vertice("Z"))
        self.assertTrue(self.g_p.adiciona_aresta(a))
        with self.assertRaises(ArestaInvalidaError):
            self.assertTrue(self.g_p.adiciona_aresta(a))
        with self.assertRaises(VerticeInvalidoError):
            self.assertTrue(self.g_p.adiciona_aresta('b1', '', 'C'))
        with self.assertRaises(VerticeInvalidoError):
            self.assertTrue(self.g_p.adiciona_aresta('b1', 'A', 'C'))
        with self.assertRaises(NotImplementedError):
            self.g_p.adiciona_aresta('')
        with self.assertRaises(NotImplementedError):
            self.g_p.adiciona_aresta('aa-bb')
        with self.assertRaises(VerticeInvalidoError):
            self.g_p.adiciona_aresta('x', 'J', 'V')
        with self.assertRaises(ArestaInvalidaError):
            self.g_p.adiciona_aresta('a1', 'J', 'C')

    def test_eq(self):
        self.assertEqual(self.g_p, self.g_p2)
        self.assertNotEqual(self.g_p, self.g_p3)
        self.assertNotEqual(self.g_p, self.g_p_sem_paralelas)
        self.assertNotEqual(self.g_p, self.g_p4)

    def test_vertices_nao_adjacentes(self):
        self.assertEqual(self.g_p.vertices_nao_adjacentes(),
                         {'J-E', 'J-P', 'J-M', 'J-T', 'J-Z', 'C-Z', 'E-P', 'E-M', 'E-T', 'E-Z', 'P-M', 'P-T', 'P-Z',
                          'M-Z'})
        self.assertEqual(self.g_d.vertices_nao_adjacentes(), {'A-C', 'A-D', 'B-C', 'B-D', 'C-D'})
        self.assertEqual(self.g_d2.vertices_nao_adjacentes(), {'A-B', 'A-C', 'A-D', 'B-C', 'B-D', 'C-D'})
        self.assertEqual(self.g_c.vertices_nao_adjacentes(), set())
        self.assertEqual(self.g_c3.vertices_nao_adjacentes(), set())

    def test_ha_laco(self):
        self.assertFalse(self.g_p.ha_laco())
        self.assertFalse(self.g_p2.ha_laco())
        self.assertFalse(self.g_p3.ha_laco())
        self.assertFalse(self.g_p4.ha_laco())
        self.assertFalse(self.g_p_sem_paralelas.ha_laco())
        self.assertFalse(self.g_d.ha_laco())
        self.assertFalse(self.g_c.ha_laco())
        self.assertFalse(self.g_c2.ha_laco())
        self.assertFalse(self.g_c3.ha_laco())
        self.assertTrue(self.g_l1.ha_laco())
        self.assertTrue(self.g_l2.ha_laco())
        self.assertTrue(self.g_l3.ha_laco())
        self.assertTrue(self.g_l4.ha_laco())
        self.assertTrue(self.g_l5.ha_laco())

    def test_grau(self):
        # Paraíba
        self.assertEqual(self.g_p.grau('J'), 1)
        self.assertEqual(self.g_p.grau('C'), 7)
        self.assertEqual(self.g_p.grau('E'), 2)
        self.assertEqual(self.g_p.grau('P'), 2)
        self.assertEqual(self.g_p.grau('M'), 2)
        self.assertEqual(self.g_p.grau('T'), 3)
        self.assertEqual(self.g_p.grau('Z'), 1)
        with self.assertRaises(VerticeInvalidoError):
            self.assertEqual(self.g_p.grau('G'), 5)

        self.assertEqual(self.g_d.grau('A'), 1)
        self.assertEqual(self.g_d.grau('C'), 0)
        self.assertNotEqual(self.g_d.grau('D'), 2)
        self.assertEqual(self.g_d2.grau('A'), 0)

        # Completos
        self.assertEqual(self.g_c.grau('J'), 3)
        self.assertEqual(self.g_c.grau('C'), 3)
        self.assertEqual(self.g_c.grau('E'), 3)
        self.assertEqual(self.g_c.grau('P'), 3)

        # Com laço. Lembrando que cada laço conta 2 vezes por vértice para cálculo do grau
        self.assertEqual(self.g_l1.grau('A'), 5)
        self.assertEqual(self.g_l2.grau('B'), 4)
        self.assertEqual(self.g_l4.grau('D'), 2)

    def test_ha_paralelas(self):
        self.assertTrue(self.g_p.ha_paralelas())
        self.assertFalse(self.g_p_sem_paralelas.ha_paralelas())
        self.assertFalse(self.g_c.ha_paralelas())
        self.assertFalse(self.g_c2.ha_paralelas())
        self.assertFalse(self.g_c3.ha_paralelas())
        self.assertTrue(self.g_l1.ha_paralelas())

    def test_arestas_sobre_vertice(self):
        self.assertEqual(self.g_p.arestas_sobre_vertice('J'), {'a1'})
        self.assertEqual(self.g_p.arestas_sobre_vertice('C'), {'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7'})
        self.assertEqual(self.g_p.arestas_sobre_vertice('M'), {'a7', 'a8'})
        self.assertEqual(self.g_l2.arestas_sobre_vertice('B'), {'a1', 'a2', 'a3'})
        self.assertEqual(self.g_d.arestas_sobre_vertice('C'), set())
        self.assertEqual(self.g_d.arestas_sobre_vertice('A'), {'asd'})
        with self.assertRaises(VerticeInvalidoError):
            self.g_p.arestas_sobre_vertice('A')

    def test_eh_completo(self):
        self.assertFalse(self.g_p.eh_completo())
        self.assertFalse((self.g_p_sem_paralelas.eh_completo()))
        self.assertTrue((self.g_c.eh_completo()))
        self.assertTrue((self.g_c2.eh_completo()))
        self.assertTrue((self.g_c3.eh_completo()))
        self.assertFalse((self.g_l1.eh_completo()))
        self.assertFalse((self.g_l2.eh_completo()))
        self.assertFalse((self.g_l3.eh_completo()))
        self.assertFalse((self.g_l4.eh_completo()))
        self.assertFalse((self.g_l5.eh_completo()))
        self.assertFalse((self.g_d.eh_completo()))
        self.assertFalse((self.g_d2.eh_completo()))
    
    def test_dfs(self):
        self.assertEqual(self.g_t1.dfs('K'), self.g_t1_dfs)
        self.assertFalse(self.g_t2.dfs('A'))
        self.assertEqual(self.g_t3.dfs('B'), self.g_t3_dfs)
        self.assertEqual(self.g_t4.dfs('B'), self.g_t4_dfs)
        self.assertEqual(self.g_t5.dfs('A'), self.g_t5_dfs)
        self.assertEqual(self.g_t6.dfs('C'), self.g_t6_dfs)
        self.assertFalse(self.g_t7.dfs('A'))
        self.assertEqual(self.g_p.dfs('T'), self.g_p_dfs)
        self.assertEqual(self.g_p4.dfs('E'), self.g_p4_dfs)
        self.assertEqual(self.g_p_sem_paralelas.dfs('Z'), self.g_p_sem_paralelas_dfs)
        self.assertEqual(self.g_c.dfs('J'), self.g_c_dfs)
        self.assertEqual(self.g_l3.dfs('C'), self.g_l3_dfs)
        self.assertFalse(self.g_d2.dfs('A'))
        with self.assertRaises(VerticeInvalidoError):
            self.g_p2.dfs('X')
    
    def test_bfs(self):
        self.assertEqual(self.g_t1.bfs('K'), self.g_t1_bfs)
        self.assertFalse(self.g_t2.bfs('A'))
        self.assertEqual(self.g_t3.bfs('B'), self.g_t3_bfs)
        self.assertEqual(self.g_t4.bfs('B'), self.g_t4_bfs)
        self.assertEqual(self.g_t5.bfs('A'), self.g_t5_bfs)
        self.assertEqual(self.g_t6.bfs('C'), self.g_t6_bfs)
        self.assertFalse(self.g_t7.bfs('A'))
        self.assertEqual(self.g_p.bfs('T'), self.g_p_bfs)
        self.assertFalse(self.g_d2.bfs('A'))
        self.assertEqual(self.g_l3.bfs('C'), self.g_l3_bfs)
        self.assertEqual(self.g_c.bfs('J'), self.g_c_bfs)
        with self.assertRaises(VerticeInvalidoError):
            self.g_p2.bfs('X')

    def test_ha_ciclo(self):
        self.assertEqual(self.g_p.ha_ciclo(), ['C', 'a2', 'E', 'a3', 'C'])
        self.assertEqual(self.c1.ha_ciclo(), ['B', 'a1', 'B'])
        self.assertEqual(self.c2.ha_ciclo(), ['B', 'a2', 'C', 'a3', 'D', 'a4', 'B'])
        self.assertEqual(self.g_t1.ha_ciclo(), ['A', '1', 'B', '11', 'F', '10', 'H', '9', 'G', '2', 'A'])
        self.assertEqual(self.g_t2.ha_ciclo(), ['A', '1', 'A'])
        self.assertFalse(self.g_t3.ha_ciclo())
        self.assertEqual(self.g_t4.ha_ciclo(), ['A', '1', 'B', '3', 'C', '2', 'A'])
        self.assertEqual(self.g_t5.ha_ciclo(), ['A', '1', 'B', '2', 'C', '3', 'A'])
        self.assertFalse(self.g_t6.ha_ciclo())
        self.assertFalse(self.g_t7.ha_ciclo())
        self.assertFalse(self.g_p_sem_paralelas.ha_ciclo())
    
    def test_conexo(self):
        self.assertTrue(self.g_p.conexo())
        self.assertFalse(self.g_d.conexo())
        self.assertFalse(self.g_d2.conexo())
        self.assertTrue(self.g_c.conexo())
        self.assertTrue(self.g_c2.conexo())
        self.assertTrue(self.g_c3.conexo())
        self.assertFalse(self.g_l1.conexo())
        self.assertFalse(self.g_l2.conexo())
        self.assertFalse(self.g_l3.conexo())
        self.assertFalse(self.g_l4.conexo())
        self.assertTrue(self.g_l5.conexo())
    
    def test_caminho(self):
        self.assertEqual(self.g_p.caminho(1), ['J', 'a1', 'C'])
        self.assertEqual(self.g_p.caminho(2), ['J', 'a1', 'C', 'a2', 'E'])
        self.assertEqual(self.g_p.caminho(3), ['J', 'a1', 'C', 'a7', 'M', 'a8', 'T'])
        self.assertEqual(self.g_p.caminho(4), ['J', 'a1', 'C', 'a7', 'M', 'a8', 'T', 'a9', 'Z'])
        self.assertFalse(self.g_p.caminho(5))
        
        self.assertEqual(self.g_p_sem_paralelas.caminho(1), ['J', 'a1', 'C'])
        self.assertEqual(self.g_p_sem_paralelas.caminho(2), ['J', 'a1', 'C', 'a2', 'E'])
        self.assertEqual(self.g_p_sem_paralelas.caminho(3), ['J', 'a1', 'C', 'a5', 'M', 'a6', 'T'])
        self.assertEqual(self.g_p_sem_paralelas.caminho(4), ['J', 'a1', 'C', 'a5', 'M', 'a6', 'T', 'a7', 'Z'])
        
        self.assertEqual(self.c1.caminho(1), ['A', 'a4', 'B'])
        
        self.assertFalse(self.g_d2.caminho(1))